
- name: (Global L0) Set local variables
  set_fact:
    cl_public_http_port: "{{ (base_global_l0_public_port | int ) }}"
    cl_p2p_http_port: "{{ (base_global_l0_p2p_port | int ) }}"
    cl_cli_http_port: "{{ (base_global_l0_cli_port | int ) }}"
    node_ip: "{{ base_prefix_ip }}{{ offset }}"
    node_info: "{{ lookup('env', 'NODES')[0] }}"

- name: (Global L0) Copy file to Docker container
  command: |
    /bin/bash -c '
    docker cp {{ lookup('env', 'SOURCE_PATH') }}/p12-files/token-key.p12 metagraph-node-1:/code/global-l0/token-key.p12 &&
    docker cp {{ lookup('env', 'SOURCE_PATH') }}/p12-files/token-key-1.p12 metagraph-node-2:/code/global-l0/token-key-1.p12 &&
    docker cp {{ lookup('env', 'SOURCE_PATH') }}/p12-files/token-key-1.p12 metagraph-node-2:/code/global-l0/token-key.p12 &&
    docker cp {{ lookup('env', 'SOURCE_PATH') }}/p12-files/token-key-2.p12 metagraph-node-3:/code/global-l0/token-key-2.p12
    docker cp {{ lookup('env', 'SOURCE_PATH') }}/p12-files/token-key-2.p12 metagraph-node-3:/code/global-l0/token-key.p12
    '


- name: (Global L0) Cleaning older directories if exists
  community.docker.docker_container_exec:
    container: metagraph-node-1
    command: |
      /bin/bash -c '
      cd global-l0 &&
      if [ -d "data" ]; then rm -r data; fi &&
      if [ -d "logs" ]; then rm -r logs; fi
      '
  when: force_genesis_bool

- name: (Global L0) Start Global L0 - Genesis
  community.docker.docker_container_exec:
    container: metagraph-node-1
    command: |
      /bin/bash -c '
      cd global-l0 &&
      nohup java -jar global-l0.jar run-genesis genesis.csv --ip {{ node_ip }} > global-l0.log 2>&1 &
      '
    env:
      CL_PUBLIC_HTTP_PORT: "{{ cl_public_http_port | string }}"
      CL_P2P_HTTP_PORT: "{{ cl_p2p_http_port | string }}"
      CL_CLI_HTTP_PORT: "{{ cl_cli_http_port | string }}"

      CL_KEYSTORE: "/code/global-l0/token-key.p12"
      CL_KEYALIAS: "token-key"
      CL_PASSWORD: "password"

      CL_APP_ENV: dev
      CL_COLLATERAL: "0"
  when: force_genesis_bool  

- name: (Global L0) Check if GL0 is Ready
  uri:
    url: "http://localhost:{{ cl_public_http_port }}/node/info"
    method: GET
    return_content: yes
  register: response
  until: response.status == 200 and ("Ready" in response.content | string or retries >= 100)
  retries: 120
  delay: 1
  vars:
    retries: 0
